# Generated by Django 2.2.19 on 2022-04-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название ингридиента'),
        ),
    ]
