# Generated by Django 2.2.19 on 2022-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220416_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название ингридиента'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredients',
            unique_together={('name', 'measurement_unit')},
        ),
    ]
