# Generated by Django 2.2.19 on 2022-04-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220416_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(default=1, max_length=16, verbose_name='Время приготовления'),
            preserve_default=False,
        ),
    ]
