# Generated by Django 2.2.19 on 2022-04-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipes_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(verbose_name='Время приготовления'),
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(related_name='recipe', to='recipes.Tags', verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='text',
            field=models.TextField(max_length=256, verbose_name='Описание рецепта'),
        ),
    ]
