# Generated by Django 2.2.19 on 2022-04-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20220416_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesingridients',
            name='ingridient',
        ),
        migrations.AddField(
            model_name='recipesingridients',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes_ingredients', related_query_name='recipes_ingredients', to='recipes.Ingredients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', related_query_name='recipe', through='recipes.RecipesIngridients', to='recipes.Ingredients', verbose_name='Ингридиенты'),
        ),
        migrations.AlterField(
            model_name='recipesingridients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_ingredients', related_query_name='recipes_ingredients', to='recipes.Recipes'),
        ),
    ]
