# Generated by Django 2.2.19 on 2022-04-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20220417_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, db_index=True, upload_to='recipes/images/', verbose_name='Картинка'),
        ),
    ]
