# Generated by Django 2.2.19 on 2022-04-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20220421_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, db_index=True, upload_to='media/recipes/images/', verbose_name='Картинка'),
        ),
    ]
