# Generated by Django 2.2.19 on 2022-04-25 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20220424_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Время приготовления не может быть отрицательным')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', related_query_name='recipe', through='recipes.RecipesIngridients', to='recipes.Ingredients', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipesingridients',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Кол-во ингредиента не может быть отрицательным')], verbose_name='Количество ингредиента'),
        ),
    ]
