# Generated by Django 2.2.19 on 2022-04-25 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20220425_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Время готовки не может быть меньше или равно 0')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipesingridients',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Кол-во ингредиента не может быть меньше или равно 0')], verbose_name='Количество ингредиента'),
        ),
    ]
